### PR TITLE
Update Composer dependencies 2019-01-30

### PR DESCRIPTION
**Pull request by schlessera**
- Updating wp-cli/shell-command (v2.0.1 => v2.0.2)
- Updating gettext/gettext (v4.6.1 => v4.6.2)
- Updating mck89/peast (v1.8.1 => v1.9.1)
- Updating justinrainbow/json-schema (5.2.7 => 5.2.8)
- Updating composer/xdebug-handler (1.3.1 => 1.3.2)
- Updating composer/ca-bundle (1.1.3 => 1.1.4)
- Updating composer/composer (1.8.0 => 1.8.2)
- Updating squizlabs/php_codesniffer (3.3.2 => 3.4.0)

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@schlessera Are you running this manually these days?

**Comment by schlessera** [comment]
@danielbachhuber Only when want to quickly test stuff. In this case, I am still working on fixing the bug that makes all the automated tests time out.

**Comment by schlessera** [comment]
@danielbachhuber I had the suspicion this had happened but didn't yet look into it.

No worries, I'll automate it on my end.

**Comment by danielbachhuber** [comment]
@schlessera I can pick it up if you'd like. I've applied to be able to use [Dependencies.io](https://www.dependencies.io/) for free. If we don't get that, then I was thinking to use Circle CI exclusively for this [based on Composer Lock Updater](https://github.com/danielbachhuber/composer-lock-updater).

**Comment by schlessera** [comment]
@danielbachhuber Dependencies.io looks very interesting. Did you apply there specifically for WP-CLI? Otherwise I can do that...

**Comment by danielbachhuber** [comment]
> Did you apply there specifically for WP-CLI? Otherwise I can do that...

Yep, I did. I'll let you know what I hear.

**Pull request merged**
