### PR TITLE
Use `ramsey/composer-install` in `Deployment` workflow

### PR DESCRIPTION
**Pull request by wojsmol**

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@wojsmol Thanks! Out of curiosity, how did you test this?

**Comment by wojsmol** [comment]
@danielbachhuber This is already used for example in https://github.com/wp-cli/.github/blob/3d55c717628f31b7d688dc9b79d8664ac2e13971/.github/workflows/reusable-testing.yml#L42-L49

**Comment by danielbachhuber** [comment]
> This is already used for example in https://github.com/wp-cli/.github/blob/3d55c717628f31b7d688dc9b79d8664ac2e13971/.github/workflows/reusable-testing.yml#L42-L49

@wojsmol Sounds good. I'll verify the deployment runs post-merge.

**Review by danielbachhuber — APPROVED** [review]

**Comment by danielbachhuber** [comment]
Looks like it built just fine: https://github.com/wp-cli/wp-cli-bundle/actions/runs/3474168022/jobs/5807128247 https://github.com/wp-cli/builds/commit/20eccc9a8cb2beaf3b2ad7c9a0f27e50af9759f6

Thanks again @wojsmol !

**Pull request merged**
