### PR TITLE
Try removing "ignore-platform-reqs" from Dependencies.yml

### PR DESCRIPTION
**Pull request by danielbachhuber**
From #71

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Going ahead and landing this so we can see what the impact is tomorrow.

**Comment by schlessera** [comment]
That actually did seem to do the trick... not sure why, though.

**Comment by danielbachhuber** [comment]
@schlessera For the same reason running `composer update` locally doesn't break the Phar. Our specific platform requirements are only used to compute the dependency graph.

**Comment by schlessera** [comment]
Sure, but that means my first interpretation of `--ignore-platform-reqs` was correct after all and was actually breaking the Phar.

**Comment by danielbachhuber** [comment]
> that means my first interpretation of `--ignore-platform-reqs` was correct after all and was actually breaking the Phar.

I don't understand. Can you explain further?

**Comment by danielbachhuber** [comment]
Oh, I think I understand what you're saying. Your original statement around including `--ignore-platform-reqs` was that doing so would break the Phar. If this is the case, then yes, this is correct.

**Pull request merged**
